---
title: "Using RFM as the new BMI"
author: "Angus Macdonald"
date: "15/12/2019"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## RFM Calculator 

### Why use RFM?

#### This app introduces the RFM, Relative Fat Mass index as the new measurement of BMI. Many of you ahve heard of the BMI, either at the doctor or at a school or university clinic. They say knowing your BMI can keep you in good health. But what happens if it is not quite true? This presentation will teach you that there are other measures instead of BMI and some might even be more applicable!

## The RFM Equation

### The RFM equation is not too disimilar to BMI in the sense that it also give you numbers to gauge your health. But that really is about it. In this presentation we will focus on the equation for men.

### RFM_Men = 64 - (20 x (height/waist))

### The nice is is that it takes into account the different body types men and woman have. If you want to know the equation for woman then you use 76 as a base number.

## Studies

### Some important studies have noted that BMI is not necessarily accurate when measuring whole body fat percentage. For example this [study](https://www.nature.com/articles/s41598-018-29362-1) suggests that RFM may be a more accurate measurement as it takes waist circumference into account.
>- [Rationale for RFM](https://www.cedars-sinai.org/blog/relative-fat-mass.html)
>- [Wikipedia](https://en.wikipedia.org/wiki/Relative_Fat_Mass)

## Using the App

### This app is very easy to use. All you need are two inputs:
- Waist Circumference
- Height

### Then all you need to do is see the caluclations results and you have your RFM! :)
### Happy measuring!








